entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: false

ping:
  entryPoint: websecure

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        Authorization: redact
        Cookie: redact
